name: Publish WAR file as Artifact

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Generate WAR file with Gradle
        run: ./gradlew war

      - name: Publish WAR file as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DProject  # Change to your desired artifact name
          path: /build/libs/DProject.war  # Adjust the path to your generated WAR file
